### ISSUE TITLE
Import error on 'xlsxwriter'

### ISSUE THREAD

**Issue by SyeedHasan** [ahmedkhlief/APT-Hunter#1]
Referenced import isn't in the requirements file. A simple install resolves the issue. 
```
Error Analyzing Sysmon logs
File Path Does Not Exist
Time Sketch Report saved as TestProject_TimeSketch.csv
Traceback (most recent call last):
  File ".\APT-Hunter.py", line 348, in <module>
    main()
  File ".\APT-Hunter.py", line 345, in main
    report()
  File ".\APT-Hunter.py", line 252, in report
    writer = pd.ExcelWriter(Report, engine='xlsxwriter', options={'encoding': 'utf-8'})
  File "C:\Python38\lib\site-packages\pandas\io\excel\_xlsxwriter.py", line 173, in __init__
    import xlsxwriter
ModuleNotFoundError: No module named 'xlsxwriter'
```

**Comment by ahmedkhlief** [comment]
Thank you . requirements updated now
