### ISSUE TITLE
 Error Analyzing Powershell Operational logs - list index out of range

### ISSUE THREAD

**Issue by scusi** [ahmedkhlief/APT-Hunter#16]
Description:    Kali GNU/Linux Rolling
Release:        2021.3
Codename:       kali-rolling
Python Verison: Python 3.9.7

```
Error Analyzing Powershell Operational logs 
ERROR:root:Traceback (most recent call last):
  File "/home/kali/sources/APT-Hunter/APT-Hunter.py", line 80, in evtxdetect_auto
    EvtxDetection.detect_events_powershell_operational_log(powershellop_path_list,input_timezone)
  File "/home/kali/sources/APT-Hunter/lib/EvtxDetection.py", line 2399, in detect_events_powershell_operational_log
    Event_desc = "Found User (" + User[0].strip() + ") run PowerShell with Command Name (" + \
IndexError: list index out of range
```

**Comment by ahmedkhlief** [comment]
Fixed , please check and let me know
