### ISSUE TITLE
UnknownTimeZoneError

### ISSUE THREAD

**Issue by MariasStory** [ahmedkhlief/APT-Hunter#17]
Hi @ahmedkhlief,
Thank for the  cool tool.
It used to work fine. Now I am getting:
```
                                                                By : Ahmed Khlief , @ahmed_khlief
                                                                Version : 2.0
                                                                                                  
Traceback (most recent call last):
  File "APT-Hunter/APT-Hunter.py", line 357, in <module>
    main()
  File "APT-Hunter/APT-Hunter.py", line 317, in main
    input_timezone=timezone(args.timezone)
  File "/usr/local/lib/python3.8/dist-packages/pytz/__init__.py", line 188, in timezone
    raise UnknownTimeZoneError(zone)
pytz.exceptions.UnknownTimeZoneError: 'evtx'
```

**Comment by ahmedkhlief** [comment]
can you please share the argument you provide when you run the tool

**Comment by ahmedkhlief** [comment]
Hi , Please check the new release (V3.0)
