### ISSUE TITLE
Error Analyzing Powershell Operational logs

### ISSUE THREAD

**Issue by normaliok** [ahmedkhlief/APT-Hunter#20]
File "E:\#Tools\APT-Hunter-main\APT-Hunter.py", line 80, in evtxdetect_auto
    EvtxDetection.detect_events_powershell_operational_log(powershellop_path_list,input_timezone)
  File "E:\#Tools\APT-Hunter-main\lib\EvtxDetection.py", line 2293, in detect_events_powershell_operational_log
    Event_desc = "Found User (" + User[
IndexError: list index out of range

**Comment by MariasStory** [comment]
I have:
```
Analyzing /data/I/Windows/system32/winevt/logs/Windows PowerShell.evtx
##### 2021-01-21 09:13:11.110047 UTC ####  ##### 2021-01-21 15:10:56.848845 UTC ####  ##### 2021-01-20 08:44:27.361172 UTC ####  Error Analyzing Sysmon logs 
ERROR:root:Traceback (most recent call last):
  File "//APT-Hunter/APT-Hunter.py", line 130, in evtxdetect_auto
    EvtxDetection.detect_events_Sysmon_log(sysmon_path_list,input_timezone)
  File "/APT-Hunter/lib/EvtxDetection.py", line 3347, in detect_events_Sysmon_log
    CommandLine[0].strip().find("*certutil*script\\:http\\[\\:\\]\\/\\/*")>-1 or
IndexError: list index out of range
```

**Comment by ahmedkhlief** [comment]
Hi Please check the new release (V3.0 )
