### ISSUE TITLE
Missing `setuptools_rust` from requirements

### ISSUE THREAD

**Issue by christalib** [ahmedkhlief/APT-Hunter#3]
Hi! When launching a dry run to install requirements, it misses the `setuptools_rust`.

```
(.env) ~/APT-Hunter >>> pip install -r Requirements.txt                                                                                                                       ±[main]
Collecting evtx
  Downloading evtx-0.6.8.tar.gz (2.2 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/xxx/APT-Hunter/.env/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-mjeg8637/evtx_f611c1c42b5446d19336a2d56bb8900b/setup.py'"'"'; __file__='"'"'/tmp/pip-install-mjeg8637/evtx_f611c1c42b5446d19336a2d56bb8900b/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-nk2jwvmk
         cwd: /tmp/pip-install-mjeg8637/evtx_f611c1c42b5446d19336a2d56bb8900b/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-mjeg8637/evtx_f611c1c42b5446d19336a2d56bb8900b/setup.py", line 5, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Thanks, the tool looks awesome!

**Comment by christalib** [comment]
Also it seems it needs a Cargo.toml to be build, am I right?

**Comment by ahmedkhlief** [comment]
Thanks for your feedback
